
#-----------------#
# Aim             #
#-----------------#

AimA:
    buffer: 1.0

AimC:
    buffer: 4.0

AimD:
    buffer: 2.0

AimE:
    buffer: 2.0


#-----------------#
# Autoclicker     #
#-----------------#

AutoclickerA:
    buffer: 4.8
    increaseBuffer: 1.6
    decreaseBuffer: 1.1
    cancelHits: true

#-----------------#
# Inventory       #
#-----------------#

InventoryA:
    cancelHits: true

InventoryB:
    cancelClicks: true

InventoryC:
    buffer: 2.0
    cancelClicks: true

ItemScroller:
    buffer: 2.0

#-----------------#
# Killaura        #
#-----------------#

KillauraC:
    cancelHits: true
    buffer: 1.0

alerts:
    # Besides broadcasting alerts to players, should they also be sent to the console?
    print-to-console: true
    # This controls whether/how alerts are relayed between servers connected to your proxy.
    # You must have 'bungee-plugin-message-channel' enabled in your Velocity config if using Velocity.
    proxy:
        # Should alerts be sent to other servers connected to your proxy?
        send: false
        # Should alerts received from other servers be announced on this server?
        receive: false

verbose:
    print-to-console: false

check-for-updates: true

client-brand:
    # Will not broadcast its brand to operators if it matches the following regex patterns
    ignored-clients:
        - "^vanilla$"
        - "^fabric$"
        - "^lunarclient:v\\d+\\.\\d+\\.\\d+-\\d{4}$"
        - "^Feather Fabric$"
        - "^labymod$"

spectators:
    # Hide all spectators with the grim.spectator permission, regardless of whether they are actively spectating.
    hide-regardless: false
    # Will only make spectators invisible in these worlds. Leave empty to allow all worlds.
    allowed-worlds:
        - ""

# How much time players are allowed before they are kicked for transaction timeout? Default = 60 seconds
max-transaction-time: 60

# Should the duplicate movement packet be cancelled?
# Mojang has fixed this issue in 1.21. This was their attempt to fix the "bucket desync". https://bugs.mojang.com/browse/MC-12363
# This setting only applies to 1.17-1.20.5 clients on 1.8 servers.
cancel-duplicate-packet: true

# Whether or not to ignore the rotation in duplicate packets
ignore-duplicate-packet-rotation: false

Simulation:
    # How much we should multiply the total advantage when the player is legitimate.
    setback-decay-multiplier: 0.999
    # How far from the possible movement the player must be to trigger a violation?
    # Measured in blocks from possible movement
    # We account for Optifine by switching trigger tables, but lowering this to 0.001 will reduce FastMath
    # and will flag if that compensation fails...
    threshold: 0.001
    # How large must a tick violation be before an immediate setback is issued?
    # -1 to disable
    immediate-setback-threshold: 0.1
    # How large the total advantage over all ticks must be before starting setbacks?
    # -1 to disable
    max-advantage: 1
    # After 50 seconds (default config), player advantage will decay from 4 blocks -> 1 block.
    # This prevents players from building up unlimited violations.
    max-ceiling: 4
    # Violation level threshold before setbacks begin
    # 1 for legacy behavior
    setback-violation-threshold: 1

# Checks if the player entered a block while moving.
Phase:
    setbackvl: 1 # Block glitches may allow wall climbing; also this check is relatively stable
    decay: 0.005

AirLiquidPlace:
    cancelvl: 0

FabricatedPlace:
    cancelvl: 5

FarPlace:
    cancelvl: 5

PositionPlace:
    cancelvl: 5

RotationPlace:
    cancelvl: 5

# NoSlow check based on predictions
# Grim accounts for netcode bugs here... hard to fail even when spam-clicking with right-click or offhand.
# Much more stable than other anticheats, but please report any false positives.
NoSlow:
    # How large of a shift counts as cheating.
    # Default is lower than other offsets
    # Flags at 0.03-0.2 reliably when NoSlow is on
    threshold: 0.001
    # Immediate setback at first flag to remove NoSlow advantage
    setbackvl: 5
    # Decay occurs when the player uses an item AND is slowed by it
    decay: 0.05

Knockback:
    # How much we should multiply the total advantage when the player is legitimate.
    setback-decay-multiplier: 0.999
    # How far from the possible movement the player must be to trigger a violation?
    threshold: 0.001
    # How large must a tick violation be before an immediate setback is issued?
    immediate-setback-threshold: 0.1
    # How large the total advantage over all ticks must be before starting setbacks?
    max-advantage: 1
    # Prevents player from accumulating too much violation and never clearing it
    max-ceiling: 4

Explosion:
    threshold: 0.001
    setbackvl: 3

TimerA:
    setbackvl: 10
    # Milliseconds the player can accumulate to use later when lagging behind.
    # Could allow 1.8 bypasses: fast-use/heal/bow if set too high; 120 ms is a good balance
    drift: 120
    # Ping at which the check will start limiting timer balance to prevent abuse.
    # May cause setbacks for legit players but only if over this ping threshold.
    # -1 to disable
    ping-abuse-limit-threshold: 1000

NegativeTimer:
    # Milliseconds lost during movement before flagging
    drift: 1200

# Same check as TimerA but for vehicles
TimerVehicle:
    # Target 1.005 timer
    setbackvl: 10

Reach:
    # How much to expand hitboxes? 0.0005 should detect 3.0005+ extra reach
    #
    # There is a forced 0.03 expansion from 1.9-1.18.1 (not 1.18.2), or some client/server combos due to
    # protocol changes and limitations. This check works best with 1.7/1.8 clients on 1.8 servers.
    threshold: 0.0005
    # Should we cancel hits that are known to be impossible?
    # Hits of 3.00-3.03 may go through but will still be flagged due to packet order limits.
    block-impossible-hits: true
    # Sends an extra packet at the end of every tick to catch more cheaters.
    # Injected into the server connection list to send just before player is removed.
    # Increases bandwidth for all players.
    # Does not reduce server performance.
    # If enabled, catches more cheaters.
    # If disabled, cheaters are still detected without false flags.
    # If not a 1.8 PvP server, do not enable this.
    enable-post-packet: false

exploit:
    allow-sprint-jumping-when-using-elytra: true
    # Mitigates ghost block placement by resyncing player when it happens.
    allow-building-on-ghostblocks: true
    distance-to-check-if-ghostblocks: 2

# Enable logging of plugins that hook into Netty on join, for debugging compatibility issues
debug-pipeline-on-join: false

# Enables experimental checks
experimental-checks: true

reset-item-usage-on-item-update: true
reset-item-usage-on-attack: true
reset-item-usage-on-slot-change: true

# Grim may cancel illegal packets, like with timer. After X packets per second are cancelled,
# should we just kick the player? Needed because some packet limiters ignore Grim's cancelled packets.
packet-spam-threshold: 100
# Enable this to print a stacktrace when a player is kicked due to packet-spam-threshold
debug-packet-cancel: false

# Grim can ensure a player falling out of flying state doesn't have a ping over X ms.
# This matters because Grim currently doesn't check flying players.
# To disable, use -1
max-ping-out-of-flying: 1000

# Maximum ping allowed when a firework boost is removed.
# Prevents high latency players from using 1 firework boost with elytra indefinitely.
max-ping-firework-boost: 1000

config-version: 9
